
category = [
    (1, 'Hair Colour Shampoo', 1),
    (2, 'Repair Shampoo', 1),
    (3, 'Colour Conditioner', 2),
    (4, 'Volume Conditioner', 2),
    (5, 'Colour Treatments', 3),
    (6, 'Hair Clippers', 4),
    (7, 'Protein Hair Treatments', 3),
    (8, 'Hair Growth Treatments', 3),
    (9, 'Hydration Hair Treatments', 3),
    (10, 'Scalp Care Shampoo', 1),
    (11, 'Cleansing & Clarifying Shampoo', 1),
    (12, 'Daily Use', 2),
    (13, 'Hair Irons', 4),
    (14, 'Curling Irons & Tongs', 4),
    (15, 'Hair Dryers', 4),
    (16, 'Blades', 5),
    (17, 'Scissors', 5),
]

links = [
    "https://www.thehaircaregroup.com/hair-care/shampoo/hair-colour-shampoo/",
    "https://www.thehaircaregroup.com/hair-care/shampoo/repair-shampoo/",
    "https://www.thehaircaregroup.com/hair-care/conditioner/colour-conditioner/",
    "https://www.thehaircaregroup.com/hair-care/conditioner/volume-conditioner/",
    "https://www.thehaircaregroup.com/hair-care/hair-treatments/colour-treatments/",
    "https://www.thehaircaregroup.com/tools-brushes/electrical/hair-clippers/",
    "https://www.thehaircaregroup.com/hair-care/hair-treatments/protein-hair-treatments/",
    "https://www.thehaircaregroup.com/hair-care/hair-treatments/hair-growth-treatments/",
    "https://www.thehaircaregroup.com/hair-care/hair-treatments/hydration-hair-treatments/",
    "https://www.thehaircaregroup.com/hair-care/shampoo/scalp-care-shampoo/",
    "https://www.thehaircaregroup.com/hair-care/shampoo/cleansing-clarifying-shampoo/",
    "https://www.thehaircaregroup.com/hair-care/conditioner/daily-use/",
    "https://www.thehaircaregroup.com/tools-brushes/electrical/hair-irons/",
    "https://www.thehaircaregroup.com/tools-brushes/electrical/curling-irons-tongs/",
    "https://www.thehaircaregroup.com/tools-brushes/electrical/hair-dryers/",
    "https://www.thehaircaregroup.com/tools-brushes/hair-cutting/blades/",
    "https://www.thehaircaregroup.com/tools-brushes/hair-cutting/scissors/",
]